#!/bin/bash

# base directory where this script is located
DIR_DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}" )" && pwd)"

# information of installation
DATETIME=`date '+%Y-%m-%d'`
COMPUTER=`scutil --get ComputerName`

# execute install.sh
LOG_FILENAME="${COMPUTER}_${DATETIME}.log"
${DIR_DOTFILES}/installer/install.sh ${DIR_DOTFILES} 2>&1 | tee ${LOG_FILENAME}
